"""Guide: The 7 Most Common Hospital Billing Errors."""

from guides import register, _embed

register("common-hospital-billing-errors", {
    "title": "The 7 Most Common Hospital Billing Errors — And How to Catch",
    "meta_description": "Billing errors appear in roughly 1 in 4 hospital bills. Learn the 7 most common error types—upcoding, duplicates, unbundling, and more—and how to catch and.",
    "published": "2026-02-20",
    "author": "BillKarma Team",
    "category": "Taking Action",
    "faqs": [
        {
            "q": "How common are hospital billing errors?",
            "a": "Very common. The HHS Office of Inspector General regularly audits Medicare claims and finds improper payment rates around 7%. AARP research shows billing errors affect a large share of patients, with individual overcharges ranging from hundreds to thousands of dollars. BillKarma's automated analysis flags potential billing issues in approximately 1 in 4 hospital bills reviewed.",
        },
        {
            "q": "What is upcoding and how do I spot it?",
            "a": "Upcoding means billing for a higher-cost service or visit level than was actually performed. The most common example is ER visit level coding: a Level 3 visit (CPT 99283, $106 Medicare) coded as a Level 5 (CPT 99285, $227 Medicare) more than doubles the charge. To spot it, request your itemized bill, find the ER visit CPT code (99281\u201399285), then compare the clinical notes to what that level requires. A straightforward visit with limited tests billed at Level 4 or 5 is a red flag.",
        },
        {
            "q": "What is unbundling in medical billing?",
            "a": "Unbundling means billing component procedures separately when a single bundled code covers all of them. The bundled code is always cheaper than the sum of its parts. CMS publishes NCCI (National Correct Coding Initiative) edits that list over 200,000 code pairs that cannot be billed together. When a hospital bills them separately anyway, you're being overcharged. Common examples include billing individual components of a colonoscopy separately rather than using CPT 45380.",
        },
        {
            "q": "What are phantom charges on a hospital bill?",
            "a": "Phantom charges are line items for services, supplies, or medications that were never actually provided. They are common on multi-day hospital stays where charges can accumulate automatically in billing systems. Check every medication listed, every supply item, and every consultation charge against your own records of what you received. Ask the nursing staff or your own notes: did a specialist actually see you? Did you receive that IV bag?",
        },
        {
            "q": "What is observation status and why does it matter so much for Medicare patients?",
            "a": "Hospitals can classify a hospital stay as either inpatient admission (covered by Medicare Part A) or observation status (covered by Part B as outpatient care). Observation status often costs Medicare patients dramatically more out of pocket because Part B has higher cost-sharing for hospital services and does not cover skilled nursing facility stays the same way Part A does. Tens of thousands of Medicare patients per year are affected. If you stayed overnight and are on Medicare, confirm your admission status in writing.",
        },
    ],
    "body": f"""
<p class="lead">BillKarma&rsquo;s automated analysis of bills from 6,000+ tracked hospitals flags potential billing issues in <strong>approximately 1 in 4 hospital bills reviewed</strong> &mdash; with upcoding and duplicate charges being the two most frequently detected error types. Hospital billing errors aren&rsquo;t rare anomalies; they&rsquo;re a predictable feature of a system where bills are generated by complex coding processes with minimal patient oversight. This guide covers the 7 most common error types, exactly how to spot each one, and how to dispute them effectively.</p>

<nav class="toc">
    <h2>In this guide</h2>
    <ol>
        <li><a href="#why-errors-common">Why billing errors are so common</a></li>
        <li><a href="#seven-errors">The 7 most common billing errors</a></li>
        <li><a href="#line-item-audit">How to do a line-item audit of your own bill</a></li>
        <li><a href="#how-to-dispute">How to dispute billing errors</a></li>
        <li><a href="#case-studies">Case studies</a></li>
        <li><a href="#faq">Frequently asked questions</a></li>
        <li><a href="#sources">Sources</a></li>
    </ol>
</nav>

<h2 id="why-errors-common">1. Why billing errors are so common</h2>

<p>Hospital billing is generated by a fragmented process: clinical staff document care, coders translate that documentation into CPT and ICD codes, billing departments submit claims, and no single person reviews the complete picture before the bill reaches you. The HHS Office of Inspector General has found <strong>Medicare improper payment rates around 7%</strong> in recent years through regular audits &mdash; and those are only the errors large enough to affect payment, not the full universe of questionable charges.</p>

<p>The Medical Billing Advocates of America estimates that a majority of hospital bills contain at least one error. KFF consistently finds that medical billing concerns rank among the top consumer healthcare grievances. And CMS&rsquo;s own improper payment reporting under the Medicare Fee-for-Service program confirms that billing inaccuracies are a structural problem, not isolated incidents.</p>

<p>The errors aren&rsquo;t always intentional fraud. Many result from coder training gaps, billing software defaults, rushed documentation, and a system where hospitals have financial incentives to bill high and let insurers negotiate down. The result is the same for patients: bills that overstate what you owe.</p>

<p>The good news: most billing errors are detectable with an itemized bill, basic knowledge of what to look for, and 30&ndash;60 minutes of your time. The seven error types below account for the vast majority of what BillKarma&rsquo;s analyzer catches.</p>

<h2 id="seven-errors">2. The 7 most common billing errors</h2>

<table>
    <thead>
        <tr>
            <th>Error Type</th>
            <th>What It Is</th>
            <th>How to Detect It</th>
            <th>Typical Impact</th>
        </tr>
    </thead>
    <tbody>
        <tr><td><strong>Upcoding</strong></td><td>Billing a higher-level service than performed</td><td>Compare CPT visit level to clinical notes</td><td>$500&ndash;$2,000+ per incident</td></tr>
        <tr><td><strong>Duplicate charges</strong></td><td>Same service billed twice or more</td><td>Sort itemized bill by date and CPT code</td><td>$50&ndash;$1,500 per duplicate</td></tr>
        <tr><td><strong>Unbundling</strong></td><td>Components billed separately instead of bundled</td><td>Cross-check NCCI edit pairs</td><td>$100&ndash;$800 per bundle</td></tr>
        <tr><td><strong>Phantom charges</strong></td><td>Charges for services never received</td><td>Compare bill to personal notes and records</td><td>$25&ndash;$500 per phantom item</td></tr>
        <tr><td><strong>Wrong patient/insurance info</strong></td><td>Coding errors causing claim processing issues</td><td>Check personal info on every bill</td><td>Delayed or denied claims</td></tr>
        <tr><td><strong>Wrong observation vs. inpatient status</strong></td><td>Outpatient &ldquo;observation&rdquo; status billed when inpatient applies</td><td>Request admission status documentation</td><td>Hundreds to thousands more out-of-pocket</td></tr>
        <tr><td><strong>Inflated room/board charges</strong></td><td>ICU billed for regular room; extra days after discharge</td><td>Match room type and dates to stay records</td><td>$500&ndash;$3,000+ per incorrect day</td></tr>
    </tbody>
</table>

<h3 id="error-upcoding">Error 1: Upcoding</h3>

<p><strong>What it is:</strong> Upcoding means billing for a higher-cost service than was actually performed. The most common and highest-dollar example is ER visit level coding, where a visit is assigned a Level 4 or Level 5 code when the actual clinical complexity supports only a Level 3.</p>

<p><strong>The numbers:</strong> ER visit level coding is the most disputed charge type in hospital billing. Here are the 2026 Medicare rates for ER visit levels:</p>

<table>
    <thead>
        <tr>
            <th>ER Visit Level</th>
            <th>CPT Code</th>
            <th>Clinical Complexity</th>
            <th>Medicare Rate (2026)</th>
            <th>Typical Hospital Charge</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>Level 3</td><td>99283</td><td>Moderate &mdash; multiple tests, moderate risk (abdominal pain, minor fracture)</td><td>$106</td><td>$900&ndash;$1,800</td></tr>
        <tr><td>Level 4</td><td>99284</td><td>High severity &mdash; urgent evaluation, high risk (chest pain, fracture)</td><td>$176</td><td>$1,800&ndash;$3,200</td></tr>
        <tr><td>Level 5</td><td>99285</td><td>Life-threatening &mdash; immediate intervention (stroke, major trauma)</td><td>$227</td><td>$2,800&ndash;$5,000+</td></tr>
    </tbody>
</table>

<p>The jump from Level 3 to Level 5 represents a 2x increase in the Medicare benchmark &mdash; and a far larger increase in actual hospital charges. Upcoding also occurs outside the ER: office visits, surgical complexity levels, and procedure codes can all be billed at higher levels than clinical documentation supports.</p>

<p><strong>How to spot it:</strong> Request your itemized bill and find the ER visit CPT code (99281&ndash;99285). Then request your medical records or ask the billing department what clinical documentation justified the assigned level. CMS publishes clear criteria for each level: Level 5 requires a high-complexity decision-making process and typically involves high-risk interventions. If your visit involved a single test and a minor complaint, Level 4 or 5 is hard to justify.</p>

<p><strong>How to dispute it:</strong> Call the billing department and ask for a &ldquo;level review.&rdquo; Reference the specific CPT code, the Medicare rate differential, and your clinical notes. Say: &ldquo;CPT 99285 requires high-complexity medical decision-making. My visit involved [describe actual treatment]. I&rsquo;d like to request a coding review for downgrade to [lower level].&rdquo; Hospitals adjust ER levels routinely when challenged with documentation.</p>

<div class="key-takeaway"><strong>Think your bill has errors?</strong> <a href="/scan">Upload your bill to BillKarma</a> &mdash; we automatically flag duplicate charges, unbundled codes, and items that exceed the Medicare rate.</div>

<h3 id="error-duplicates">Error 2: Duplicate charges</h3>

<p><strong>What it is:</strong> The same service, medication, or supply billed more than once. Duplicate charges are especially common on multi-day inpatient stays where billing systems may log daily charges and individual administrations separately. IV bags, daily medications, and routine labs are the most frequently duplicated items.</p>

<p><strong>How to spot it:</strong> Sort your itemized bill by CPT code and date. Look for the same code appearing on the same date without clinical justification. Also look for the same service appearing under two different billing codes (e.g., a chest X-ray billed as both CPT 71046 and as a line item under the radiology department separately).</p>

<p><strong>How to dispute it:</strong> Point out the specific duplicate line items &mdash; date, CPT code, and charge amount &mdash; and ask for a corrected bill. Billing departments will generally remove clear duplicates without resistance because they have no documentation to justify double-billing the same service on the same day.</p>

<h3 id="error-unbundling">Error 3: Unbundling</h3>

<p><strong>What it is:</strong> Billing component procedures separately when a single bundled CPT code covers all of them. Because the bundled code is priced below the sum of its parts, unbundling results in a higher charge. CMS publishes NCCI (National Correct Coding Initiative) edits listing <strong>over 200,000 code pairs</strong> that cannot be billed together when one comprehensive code applies. Hospitals still attempt it.</p>

<p><strong>Example:</strong> A colonoscopy with biopsy is correctly billed as CPT 45380 (Medicare rate: $198). Unbundling would bill the colonoscopy (45378) and the biopsy (45380) as separate line items, each with their own charge, totaling more than the bundled rate.</p>

<p><strong>How to spot it:</strong> Look for procedure codes from the same clinical area on the same date, especially codes that appear to be components of a single procedure. BillKarma&rsquo;s analyzer checks your bill against the NCCI edit list automatically.</p>

<p><strong>How to dispute it:</strong> Reference the NCCI edit. Say: &ldquo;CMS NCCI edits indicate that CPT [code A] and CPT [code B] cannot be billed together when [bundled code] applies. Please review and rebill using the appropriate bundled code.&rdquo;</p>

<h3 id="error-phantom">Error 4: Phantom charges</h3>

<p><strong>What it is:</strong> Charges for services, medications, or supplies that were never actually provided. Phantom charges can result from billing system errors, miscommunication between floors, or in some cases deliberate padding. Common examples include consultations by specialists who were called but never arrived, medications listed but not administered, and supplies used for another patient.</p>

<p><strong>How to spot it:</strong> Keep a personal log during your hospital stay: which medications you actually received, which specialists actually examined you, which tests were actually performed. Compare this log to your itemized bill line by line. If you see a consultation charge for a specialist you never met, or a medication you don&rsquo;t recognize, flag it.</p>

<p><strong>How to dispute it:</strong> Request the nursing notes and medication administration record (MAR) for your stay &mdash; you are entitled to these under HIPAA. If the records show the medication was not administered or the consultation was not completed, dispute the charge with the records as evidence.</p>

<h3 id="error-wrong-info">Error 5: Wrong patient or insurance information</h3>

<p><strong>What it is:</strong> Data entry errors affecting patient name, date of birth, insurance ID number, group number, or insurance plan. These errors cause claims to be denied or processed incorrectly, which can result in you being billed directly for an amount your insurance should have covered.</p>

<p><strong>How to spot it:</strong> Check your name, date of birth, and insurance information on every bill and every Explanation of Benefits (EOB) you receive. Verify that the insurance plan listed matches your actual plan. A single transposed digit in an insurance ID can cause a claim denial that generates a patient bill for the full amount.</p>

<p><strong>How to dispute it:</strong> Contact the billing department immediately with the correct information. Ask them to refile the claim with the corrected data. Do not pay the bill until the corrected claim has been processed by your insurance.</p>

<h3 id="error-observation">Error 6: Incorrect observation vs. inpatient status</h3>

<p><strong>What it is:</strong> Hospitals can classify a hospital stay as either an inpatient admission (covered by Medicare Part A) or observation status (covered by Medicare Part B as outpatient care). The cost difference for Medicare patients is enormous: Part B has different cost-sharing than Part A, and observation status patients do not qualify for Medicare-covered skilled nursing facility care afterward. CMS data shows tens of thousands of Medicare patients per year are affected by observation status classification issues.</p>

<p><strong>Why it happens:</strong> Hospitals sometimes classify patients as observation to reduce their risk of Medicare audits and take-backs for short inpatient stays. The financial incentives push toward observation status; the cost falls on the patient.</p>

<p><strong>How to spot it:</strong> If you are on Medicare and stayed overnight in the hospital, ask in writing: &ldquo;Was I admitted as an inpatient or placed in observation status?&rdquo; You must be notified under the NOTICE Act (the Medicare Outpatient Observation Notice, or MOON), but not all hospitals comply fully.</p>

<p><strong>How to dispute it:</strong> File a written appeal with the hospital and your Medicare Administrative Contractor (MAC). The <a href="/guides/observation-status/">observation status guide</a> covers the full appeals process. The stakes are high enough that engaging a patient advocate is worth considering.</p>

<h3 id="error-room-board">Error 7: Inflated room and board charges</h3>

<p><strong>What it is:</strong> Being billed for a higher-acuity room type than you actually occupied (ICU rate billed when you were in a standard medical-surgical room), or being billed for extra days after your discharge date. Room and board is one of the highest per-day costs on a hospital bill, so even a single incorrect day is significant.</p>

<p><strong>How to spot it:</strong> Compare the room type on your bill to your actual room. ICU rooms typically cost $3,000&ndash;$5,000 per day; standard rooms typically cost $1,000&ndash;$2,500. If the bill shows ICU charges and you were never in the ICU, that&rsquo;s a direct error. Also verify that the admission and discharge dates on your bill match your actual dates.</p>

<p><strong>How to dispute it:</strong> Request your hospital&rsquo;s room assignment records and compare them to the bill. If you were discharged at 10am but the bill includes a charge for that full day (or the next day), dispute it with your discharge paperwork as evidence.</p>

<div class="key-takeaway">
    <strong>See which of these errors BillKarma checks automatically.</strong> Our analyzer runs your bill against Medicare rates, the NCCI edit list, and duplicate detection logic. <a href="/scan">Upload your bill</a> to get a flagged line-item report in minutes.
</div>

<h2 id="line-item-audit">3. How to do a line-item audit of your own bill</h2>

<p>You don&rsquo;t need a professional billing advocate to catch most errors. Here&rsquo;s the process, step by step.</p>

<p><strong>Step 1: Request an itemized bill.</strong> Call the hospital billing department and ask specifically for an <em>itemized bill with CPT codes</em>. A summary statement showing only totals by category is not enough. Every individual service, medication, supply, and procedure should appear as a separate line item with its CPT or HCPCS code and charge.</p>

<p><strong>Step 2: Request your medical records.</strong> Request the relevant portions of your medical record: nursing notes, medication administration record (MAR), physician notes, and the discharge summary. You are entitled to these under HIPAA. The hospital has 30 days to provide them and can charge a reasonable fee for copies.</p>

<p><strong>Step 3: Sort and organize the bill.</strong> Sort line items by date and by CPT code. Group similar codes together. This makes duplicates immediately visible.</p>

<p><strong>Step 4: Look up Medicare rates for each CPT code.</strong> Use BillKarma&rsquo;s calculator to look up the Medicare facility rate for each CPT code on your bill. The Medicare rate is your benchmark &mdash; not what you should pay, but what the procedure is actually worth based on CMS&rsquo;s cost analysis. Flag any charges that look dramatically different from the Medicare rate or from what other hospitals charge.</p>

<p><strong>Step 5: Cross-reference with your records.</strong> Go line by line through the bill and match each charge to something in your medical records or your personal notes. A charge with no corresponding record entry is a phantom charge candidate.</p>

<p><strong>Step 6: Check the NCCI edits for procedure pairs.</strong> If you see multiple procedure codes from the same clinical area on the same date, check whether they appear on the NCCI unbundling list. BillKarma does this automatically, or you can look up code pairs on the CMS NCCI tools page.</p>

<p>Here is what a flagged itemized bill looks like:</p>

<div class="bill-example">
    <div class="bill-header">Itemized Statement &mdash; Riverside General Hospital &mdash; Stay: 03/04/2026&ndash;03/06/2026</div>
    <div class="line-item">
        <span>99284 &mdash; ER Visit Level 4 (03/04)</span>
        <span>$3,140.00</span>
    </div>
    <div class="line-item">
        <span>71046 &mdash; Chest X-ray, 2 views (03/04)</span>
        <span>$418.00</span>
    </div>
    <div class="line-item flagged">
        <span>71046 &mdash; Chest X-ray, 2 views (03/04) &nbsp; &#9888; <em>Duplicate &mdash; same CPT code and date as line above</em></span>
        <span>$418.00</span>
    </div>
    <div class="line-item">
        <span>80053 &mdash; Comprehensive metabolic panel (03/04)</span>
        <span>$312.00</span>
    </div>
    <div class="line-item error">
        <span>99285 &mdash; ER Visit Level 5 (03/04) &nbsp; &#10060; <em>Cannot bill two ER visit levels for the same encounter</em></span>
        <span>$4,200.00</span>
    </div>
    <div class="line-item">
        <span>Room &amp; Board &mdash; Med/Surg (03/04)</span>
        <span>$1,840.00</span>
    </div>
    <div class="line-item">
        <span>Room &amp; Board &mdash; Med/Surg (03/05)</span>
        <span>$1,840.00</span>
    </div>
    <div class="line-item flagged">
        <span>Room &amp; Board &mdash; ICU (03/05) &nbsp; &#9888; <em>ICU room billed on same date as Med/Surg room &mdash; verify room assignment</em></span>
        <span>$4,200.00</span>
    </div>
    <div class="line-item flagged">
        <span>Consult &mdash; Cardiology (03/05) &nbsp; &#9888; <em>Verify specialist actually visited &mdash; no note in medical record</em></span>
        <span>$580.00</span>
    </div>
    <div class="line-total">
        <span>TOTAL CHARGED</span>
        <span>$16,948.00</span>
    </div>
    <div class="line-total">
        <span>Flagged / disputed amount</span>
        <span>$9,398.00</span>
    </div>
</div>

<div class="key-takeaway">
    <strong>Check if your charge looks right.</strong> Enter any CPT code and the amount you were charged to see how it compares to the Medicare rate and flag potential overbilling.
</div>

{_embed(mode="markup", title="Check if your charge looks right", subtitle="Enter the CPT code and billed amount from your itemized bill.", height="420")}

<h2 id="how-to-dispute">4. How to dispute billing errors</h2>

<p>Once you&rsquo;ve identified a potential error, the dispute process is straightforward. Most billing errors are resolved at the billing department level without needing to escalate.</p>

<p><strong>Step 1: Call the billing department first.</strong> Most errors can be corrected with a single phone call if you are specific. Identify the line item by CPT code, date of service, and dollar amount. State the specific reason you believe it is incorrect (duplicate, wrong level, NCCI edit violation, etc.). Ask for a correction or a formal coding review.</p>

<p><strong>Step 2: Follow up in writing.</strong> If the phone call doesn&rsquo;t resolve it within 10 days, send a written dispute. Include: your name and account number, the specific line items in question, your reason for dispute, and the supporting documentation (duplicate entries, NCCI code pair, medical record discrepancy). Send via certified mail or through the hospital&rsquo;s patient portal with a record of submission.</p>

<p><strong>Step 3: Request a formal billing review.</strong> Every hospital has a billing review process. Ask specifically: &ldquo;I would like to request a formal billing review for these specific charges.&rdquo; This triggers an internal audit and typically results in a written response within 30 days.</p>

<p><strong>Step 4: Involve your insurance company.</strong> If the error affected how your claim was processed, call your insurer and ask them to request a corrected claim from the hospital. Insurers have leverage that individual patients don&rsquo;t &mdash; hospitals respond more quickly to insurer requests for corrected claims.</p>

<p><strong>Step 5: Escalate if needed.</strong> If the hospital refuses to correct a clear error, escalate to your state&rsquo;s insurance commissioner (for insurance-related billing disputes) or your state attorney general&rsquo;s consumer protection division. For Medicare patients, contact your Medicare Administrative Contractor (MAC). For detailed dispute letter templates, see our <a href="/guides/how-to-dispute-a-medical-bill/">complete dispute guide</a>.</p>

<p><strong>Do not pay the disputed amount while the dispute is open.</strong> Ask the hospital to place the disputed items on hold while the review is in progress. Most hospitals will not send an account to collections while a formal billing review is pending.</p>

<div class="key-takeaway">
    <strong>Need help with the dispute?</strong> Use our <a href="/calculator">Medicare rate calculator</a> to document the benchmark rate for each disputed code, then follow the <a href="/guides/how-to-dispute-a-medical-bill/">step-by-step dispute guide</a> with letter templates you can send today.
</div>

<h2 id="case-studies">5. Case studies</h2>

<div class="case-study">
    <h3>Upcoded ER visit: Level 5 billed for a kidney stone</h3>
    <p>A patient in Arizona went to the emergency room with flank pain and was diagnosed with a kidney stone (nephrolithiasis). Treatment consisted of a urinalysis (CPT 81001), abdominal CT (CPT 74178), IV fluids, and a pain medication injection. Total time in the ER: 3.5 hours. Discharge was with a prescription and a referral to urology.</p>
    <p>The bill showed CPT 99285 (Level 5 ER visit, $4,890 billed) and a facility charge consistent with a life-threatening emergency. Medicare&rsquo;s rate for 99285 is $227; Medicare&rsquo;s rate for 99284 (Level 4) is $176; for 99283 (Level 3) it is $106.</p>
    <p>The patient requested a coding review, noting that his visit involved moderate clinical decision-making, one imaging study, and no high-risk interventions &mdash; consistent with Level 3 or Level 4 criteria. The hospital reviewed and downgraded to CPT 99284. The facility charge was reduced from $4,890 to $2,940. <strong>Total recovered: $1,950.</strong></p>
</div>

<div class="case-study">
    <h3>Duplicate lab charges on a 4-day inpatient stay</h3>
    <p>A patient in Tennessee had a 4-day hospitalization following an appendectomy (CPT 44950). After requesting an itemized bill with CPT codes, she found three instances of CPT 80053 (comprehensive metabolic panel, Medicare rate $14) billed twice on the same date &mdash; once under the laboratory department and once under the floor nursing charge. She also found CPT 85027 (complete blood count) duplicated on two of the four days.</p>
    <p>Total duplicate charges: 5 line items averaging $280 each at the hospital&rsquo;s billed rate. She called the billing department, listed each duplicate by date and CPT code, and asked for a corrected bill. All five were removed without escalation. <strong>Total removed: $1,400.</strong></p>
</div>

<div class="case-study">
    <h3>Unbundled colonoscopy charges</h3>
    <p>A patient in Florida had a screening colonoscopy with biopsy. The correct CPT code for a colonoscopy with biopsy is 45380 (Medicare rate: $198). His bill instead showed CPT 45378 (diagnostic colonoscopy, billed at $3,200) and CPT 43239 (upper GI biopsy, billed at $1,800) on the same date &mdash; an apparent unbundling error mixing colonoscopy and upper GI codes, and failing to apply the correct comprehensive code.</p>
    <p>BillKarma&rsquo;s analyzer flagged the combination as an NCCI edit violation. The patient contacted the billing department referencing the NCCI edit and asked for rebilling under CPT 45380. After a coding review, the hospital corrected the claim and reprocessed. His out-of-pocket responsibility dropped from $980 (after insurance applied to the unbundled charges) to $0 (the procedure qualified as a preventive screening under his plan when billed correctly). <strong>Total impact: $980 out-of-pocket eliminated.</strong></p>
</div>

<h2 id="faq">Frequently asked questions</h2>

<div class="faq-section">
    <div class="faq-item">
        <h3>How common are hospital billing errors?</h3>
        <p>Very common. The HHS Office of Inspector General finds Medicare improper payment rates around 7% in annual audits. BillKarma&rsquo;s automated analysis flags potential billing issues in approximately 1 in 4 hospital bills reviewed. AARP research shows billing errors affect a large share of patients, with individual overcharges ranging from hundreds to thousands of dollars. Check your own bill at <a href="/hospitals/">our hospital directory</a> to see if your hospital has a pattern of specific billing issues.</p>
    </div>

    <div class="faq-item">
        <h3>What is upcoding and how do I spot it?</h3>
        <p>Upcoding means billing for a higher-level service than was performed. The most common example is ER visit level coding: a Level 3 visit (CPT 99283, $106 Medicare rate) coded as Level 5 (CPT 99285, $227 Medicare rate) more than doubles the charge. To spot it, request your itemized bill, find the ER visit CPT code (99281&ndash;99285), then compare the clinical notes to the criteria for that level. Use our <a href="/calculator">calculator</a> to see what Medicare pays at each level.</p>
    </div>

    <div class="faq-item">
        <h3>What is unbundling in medical billing?</h3>
        <p>Unbundling means billing component procedures separately when a single bundled code should cover all of them. The bundled code is always cheaper than the sum of its parts, so unbundling inflates your bill. CMS publishes NCCI edits listing over 200,000 code pairs that cannot be billed together. <a href="/scan">BillKarma&rsquo;s bill analyzer</a> checks your bill against the NCCI list automatically.</p>
    </div>

    <div class="faq-item">
        <h3>What are phantom charges on a hospital bill?</h3>
        <p>Phantom charges are line items for services, supplies, or medications never actually provided. They are common on multi-day stays where billing systems accumulate charges automatically. Keep a log during your stay of what medications you received, which specialists actually saw you, and which tests were performed. Compare this log to your itemized bill and request the medication administration record (MAR) if anything looks wrong.</p>
    </div>

    <div class="faq-item">
        <h3>What is observation status and why does it matter for Medicare patients?</h3>
        <p>Hospitals can classify a stay as inpatient admission (Medicare Part A) or observation status (outpatient, Medicare Part B). Observation status often costs Medicare patients dramatically more out of pocket and does not qualify them for Medicare-covered skilled nursing facility care afterward. If you are on Medicare and stayed overnight, ask in writing whether you were admitted as inpatient or placed on observation. See our <a href="/guides/observation-status/">observation status guide</a> for the full appeals process.</p>
    </div>

    <div class="faq-item">
        <h3>Should I pay my hospital bill before disputing it?</h3>
        <p>No. If you have identified specific errors or are requesting a billing review, ask the hospital to place the disputed items on hold while the review is in progress. Do not pay the disputed amount before the review is resolved. Most hospitals will not send an account to collections while a formal billing review is pending. For a complete dispute process, see our <a href="/guides/how-to-dispute-a-medical-bill/">dispute guide</a>.</p>
    </div>
</div>

<h2 id="sources">Sources</h2>

<ul class="sources-list">
    <li><a href="https://oig.hhs.gov/reports-and-publications/medicare-and-medicaid-fraud-waste-and-abuse/" target="_blank" rel="noopener">HHS Office of Inspector General: Medicare Improper Payment Reporting and Audit Results</a></li>
    <li><a href="https://www.aarp.org/money/personal-finance/info-2021/medical-billing-errors.html" target="_blank" rel="noopener">AARP: Medical Billing Errors &mdash; What Patients Need to Know</a></li>
    <li><a href="https://www.kff.org/health-costs/issue-brief/data-note-americans-challenges-with-health-care-costs/" target="_blank" rel="noopener">KFF: Americans&rsquo; Challenges with Health Care Costs &mdash; Medical Billing Concerns</a></li>
    <li><a href="https://www.cms.gov/priorities/key-initiatives/improper-payments" target="_blank" rel="noopener">CMS: Medicare Fee-for-Service Improper Payment Rate Reporting</a></li>
    <li><a href="https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits" target="_blank" rel="noopener">CMS: National Correct Coding Initiative (NCCI) Edits &mdash; Unbundling Prevention</a></li>
    <li><a href="https://www.cms.gov/medicare/payment/fee-schedules/hospital-outpatient" target="_blank" rel="noopener">CMS: Outpatient Prospective Payment System (OPPS) &mdash; 2026 Medicare Rates</a></li>
    <li><a href="https://www.medicalbillingadvocatesofamerica.com/" target="_blank" rel="noopener">Medical Billing Advocates of America: Billing Error Rates and Dispute Outcomes</a></li>
</ul>
""",
})
