"""Guide: How to Read Your Explanation of Benefits (EOB)."""

from guides import register, _embed

register("explanation-of-benefits-eob-guide", {
    "title": "How to Read Your Explanation of Benefits (EOB)",
    "meta_description": "An EOB is not a bill—but it tells you exactly what you owe. Learn every section, catch common errors, decode denial codes, and know when your EOB and bill don't match.",
    "published": "2026-04-06",
    "author": "BillKarma Team",
    "category": "Insurance Basics",
    "faqs": [
        {
            "q": "Is an Explanation of Benefits (EOB) the same as a bill?",
            "a": "No. An EOB is a summary statement from your insurance company explaining how it processed a claim. It shows what was billed, what the insurer paid, and what portion you are responsible for&mdash;but it is not a demand for payment. The actual bill comes from your provider. The EOB is your tool for verifying that the provider&rsquo;s bill matches what your insurer says you owe before you pay anything.",
        },
        {
            "q": "What should I do if my EOB says I owe more than my provider&rsquo;s bill?",
            "a": "Pay the lower amount. If your provider is in-network and bills you less than the EOB shows as your responsibility, the provider has agreed to accept less. Pay only what the provider invoices you for. If the EOB amount is higher than expected, call your insurer to understand why&mdash;it may indicate a processing error or that the claim was applied to a deductible you weren&rsquo;t aware of.",
        },
        {
            "q": "How long do I have to appeal a denied claim on my EOB?",
            "a": "For most plans covered by ERISA (employer-sponsored plans), you have at least 180 days from the date of the denial to file an internal appeal with your insurer. After an internal appeal is denied, you have the right to an external review by an independent organization. State-regulated individual and small-group plans have similar appeal rights under the ACA. The appeal deadline is printed on your EOB&mdash;never miss it.",
        },
    ],
    "body": f"""<article>

<div class="answer-box" style="border-left: 4px solid #22c55e; padding: 1rem 1.25rem; background: #f0fdf4; margin-bottom: 1.5rem;">
    <strong>The short answer:</strong> An EOB is not a bill&mdash;it&rsquo;s your insurer&rsquo;s report card on a claim. The critical number is &ldquo;Patient Responsibility&rdquo; or &ldquo;Your Share.&rdquo; Before you pay any medical bill, compare it to the EOB for the same date of service. If the numbers don&rsquo;t match, do not pay until you understand why.
</div>

<p class="lead">Your Explanation of Benefits (EOB) is one of the most important documents in healthcare&mdash;and one of the most misunderstood. Most patients glance at it, assume it&rsquo;s a bill, and either pay or ignore it. In reality, your EOB is your insurer&rsquo;s detailed accounting of how a claim was processed, and reading it carefully is the single best way to catch billing errors, verify your cost-sharing is correct, and know when to appeal a denial.</p>

<nav class="toc">
    <h2>In this guide</h2>
    <ol>
        <li><a href="#eob-vs-bill">EOB vs. actual bill: the critical difference</a></li>
        <li><a href="#eob-sections">What each section of the EOB means</a></li>
        <li><a href="#key-amounts">The four key dollar amounts explained</a></li>
        <li><a href="#common-eob-errors">Common EOB errors to catch</a></li>
        <li><a href="#denial-codes">Denial codes explained</a></li>
        <li><a href="#eob-bill-mismatch">What to do when EOB and bill don&rsquo;t match</a></li>
        <li><a href="#how-to-appeal">How to appeal a denial or incorrect processing</a></li>
    </ol>
</nav>

<h2 id="eob-vs-bill">EOB vs. actual bill: the critical difference</h2>

<p>An EOB is generated by your insurance company every time a provider submits a claim for your care. It is your insurer&rsquo;s explanation of how they processed the claim&mdash;how much they allowed, how much they paid, and how much they are telling you that you owe. But it is not a request for payment.</p>

<p>The actual bill comes from the provider (the hospital, physician group, or lab). The provider&rsquo;s bill reflects what they believe you owe based on your insurance contract and your cost-sharing obligations. The two documents should align, but they often don&rsquo;t&mdash;for several reasons:</p>

<ul>
    <li>The provider may have billed for services not yet processed by your insurer</li>
    <li>Your insurer may have paid a different amount than the provider expected under their contract</li>
    <li>The provider may have made a billing error that your insurer caught (and adjusted) or didn&rsquo;t catch</li>
    <li>Your deductible or out-of-pocket accumulator may be at a different point than the provider&rsquo;s records show</li>
</ul>

<p><strong>The rule:</strong> Never pay a provider bill until you have the EOB for the same date of service. The EOB is your independent verification of what you actually owe.</p>

<h2 id="eob-sections">What each section of the EOB means</h2>

<p>EOB formats vary by insurer, but every EOB contains the same core information. Here is what to look for in each section:</p>

<h3>Header information</h3>
<ul>
    <li><strong>Member name and ID:</strong> Verify this is your claim, not a family member&rsquo;s. Wrong member ID is a common error that can affect your deductible and out-of-pocket tracking.</li>
    <li><strong>Date of service:</strong> The date the care was provided. If you had multiple visits, each generates a separate EOB (or a separate line on a combined EOB).</li>
    <li><strong>Claim number:</strong> Reference this number in all communications with your insurer about this claim.</li>
    <li><strong>Provider name:</strong> The name of the provider who submitted the claim. Verify this is the provider you actually saw.</li>
</ul>

<h3>Service lines</h3>
<p>Each procedure, service, or supply appears as a separate line. Each line shows the CPT or HCPCS code, a description, and the dollar amounts broken out across the key columns. This is where you need to compare carefully against your itemized provider bill.</p>

<h3>Totals section</h3>
<p>A summary of all amounts across all service lines: total billed, total not covered, total allowed, insurance paid, and your responsibility.</p>

<h3>Notes and remark codes</h3>
<p>Every EOB includes remarks explaining how each line was processed. These are typically short codes (like &ldquo;PR-1&rdquo; or &ldquo;CO-45&rdquo;) with brief descriptions. See the denial codes section below for the most important ones.</p>

<h2 id="key-amounts">The four key dollar amounts explained</h2>

<p>Every EOB shows four distinct dollar amounts for each claim. Understanding what each one represents is the foundation of reading your EOB correctly.</p>

<h3>1. Billed amount (Charged Amount)</h3>
<p>This is what the provider submitted to your insurer&mdash;the chargemaster or full list price. This number is almost always irrelevant to what you will actually pay. In-network providers have contractually agreed to accept much less than their billed rates.</p>

<h3>2. Allowed amount (Eligible Expense, Negotiated Rate)</h3>
<p>This is the amount your insurer has determined is the maximum payable for this service under your plan. For in-network providers, this is the contracted rate. For out-of-network providers, it is the &ldquo;usual and customary&rdquo; rate set by the insurer, which can be much lower than what the provider actually charges.</p>
<p>The <strong>allowed amount is the basis for all your cost-sharing calculations</strong>. Your deductible, coinsurance, and out-of-pocket maximum are calculated as a percentage of the allowed amount, not the billed amount.</p>

<h3>3. Insurance paid (Plan Paid)</h3>
<p>The dollar amount your insurer actually paid to the provider, after applying your deductible and calculating coinsurance. If this number is $0, it means the claim was either fully applied to your deductible or denied. The notes section will tell you which.</p>

<h3>4. Patient responsibility (Your Share)</h3>
<p>The amount your insurer says you owe to the provider. This includes any deductible applied, your coinsurance portion, and any copay. This should match what the provider bills you&mdash;though it often doesn&rsquo;t.</p>

{_embed(mode="cost", cpt="99213", title="Compare your allowed amount to Medicare rates", subtitle="See how your insurer&rsquo;s allowed amount compares to the Medicare benchmark.")}

<h2 id="common-eob-errors">Common EOB errors to catch</h2>

<p>EOBs are generated by automated systems processing large volumes of claims. Errors occur regularly. The most common and financially significant ones are:</p>

<h3>Wrong deductible applied</h3>
<p>Your insurer applied your out-of-network deductible to a claim from an in-network provider, or vice versa. This can add hundreds or thousands to your patient responsibility. Check: is the provider listed as in-network on your EOB? If not, and you believe they are in-network, call your insurer immediately&mdash;this is the most valuable EOB error to catch.</p>

<h3>Claim processed under wrong plan year</h3>
<p>If you received care near the end of your plan year (December for calendar-year plans), the claim may have been processed in the wrong year&mdash;before your deductible was credited rather than after. The result: you pay your full deductible again instead of the small remaining balance you expected.</p>

<h3>Duplicate claim processing</h3>
<p>The same service processed twice, resulting in two separate patient responsibility entries. Compare your EOBs for the same date of service to check for duplicates.</p>

<h3>Wrong member applied</h3>
<p>On a family plan, a claim for one family member is applied to another member&rsquo;s deductible and out-of-pocket accumulator. This can both inflate one person&rsquo;s tracked expenses and leave another under-credited.</p>

<h3>Services denied as &ldquo;not covered&rdquo; that are covered</h3>
<p>Your insurer denies a service as not covered under your plan, but the service is in fact covered. This is more common with preventive care (which must be covered at 100% under the ACA for in-network providers), mental health services, and prescription drugs. Always verify a denial against your Summary of Benefits and Coverage.</p>

<h2 id="denial-codes">Denial codes explained</h2>

<p>EOBs use standardized remark and reason codes to explain how each line was processed. The most common codes you will encounter are from the CARC (Claim Adjustment Reason Code) and RARC (Remittance Advice Remark Code) systems. Here are the codes patients encounter most often:</p>

<table>
    <thead>
        <tr>
            <th>Code</th>
            <th>What it means</th>
            <th>What to do</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>CO-45</td>
            <td>Charge exceeds fee schedule/maximum allowable; contractual adjustment</td>
            <td>Normal for in-network claims. The provider accepted less than billed. No action needed.</td>
        </tr>
        <tr>
            <td>PR-1</td>
            <td>Deductible amount</td>
            <td>Applied to your deductible. Verify the deductible amount is correct for your plan year.</td>
        </tr>
        <tr>
            <td>PR-2</td>
            <td>Coinsurance amount</td>
            <td>Your share of the allowed amount after deductible. Verify percentage matches your plan.</td>
        </tr>
        <tr>
            <td>PR-3</td>
            <td>Copay amount</td>
            <td>Fixed copay per your plan terms. Verify against your Summary of Benefits.</td>
        </tr>
        <tr>
            <td>CO-4</td>
            <td>Service/procedure is inconsistent with the modifier</td>
            <td>Billing error by provider. Contact provider&rsquo;s billing department.</td>
        </tr>
        <tr>
            <td>CO-11</td>
            <td>Diagnosis inconsistent with the procedure</td>
            <td>Possible coding error. Ask provider to verify and resubmit if incorrect.</td>
        </tr>
        <tr>
            <td>CO-50</td>
            <td>Non-covered service; not deemed a medical necessity by payer</td>
            <td>Appeal with a letter of medical necessity from your treating physician.</td>
        </tr>
        <tr>
            <td>CO-97</td>
            <td>Payment is included in the allowance for another service/procedure</td>
            <td>Bundling rule applied. May be correct (global surgical period) or an error. Verify with provider.</td>
        </tr>
        <tr>
            <td>MA130</td>
            <td>Incomplete or invalid claim</td>
            <td>Provider needs to resubmit with corrected information.</td>
        </tr>
    </tbody>
</table>

<h2 id="eob-bill-mismatch">What to do when EOB and bill don&rsquo;t match</h2>

<p>When the patient responsibility on your EOB differs from what the provider is billing you, follow this process:</p>

<ol>
    <li><strong>Match service dates and CPT codes.</strong> Make sure you are comparing the EOB and the provider bill for the exact same date of service and the same procedure codes. A mismatch might simply be that the provider submitted additional codes not yet processed.</li>
    <li><strong>Check whether all claims have been processed.</strong> Call your insurer and ask whether all claims for this date of service have been processed. If claims are still pending, wait for the final EOB before taking action.</li>
    <li><strong>If the provider bill is higher than the EOB patient responsibility:</strong> Call the provider billing department. Provide your claim number and EOB patient responsibility amount. Ask why their bill is higher. For in-network providers, they can only collect your EOB patient responsibility amount&mdash;they cannot bill you more than the insurer&rsquo;s allowed amount under their contract.</li>
    <li><strong>If the EOB patient responsibility is higher than expected:</strong> Call your insurer. Ask them to walk through how the claim was processed. Check whether your deductible was applied correctly, whether the provider was processed as in-network, and whether any services were incorrectly denied.</li>
    <li><strong>Document everything.</strong> Note the date, name of representative, and what you were told. Follow up in writing if the issue is not resolved in a single call.</li>
</ol>

<h2 id="how-to-appeal">How to appeal a denial or incorrect processing</h2>

<p>If your EOB shows a denial you believe is incorrect, you have the right to appeal. The process:</p>

<ol>
    <li><strong>Identify the denial reason.</strong> Read the denial code and remarks carefully. Understanding why the claim was denied tells you what evidence you need for the appeal.</li>
    <li><strong>File an internal appeal.</strong> Submit a written appeal to your insurer within the deadline printed on your EOB (typically 180 days for ERISA plans). Include a clear explanation of why you believe the denial is incorrect and any supporting documentation: a letter of medical necessity from your physician, evidence of prior authorization, or your plan documents showing the service is covered.</li>
    <li><strong>Request an expedited appeal for urgent care.</strong> If the denial involves ongoing care that you need urgently, you can request an expedited review (typically 72-hour turnaround) rather than the standard 30&ndash;60 day internal appeal process.</li>
    <li><strong>File an external review if the internal appeal fails.</strong> If your internal appeal is denied, you have the right to an independent external review by an organization not affiliated with your insurer. External reviewers overturn insurer denials at a significant rate&mdash;especially for medical necessity denials.</li>
    <li><strong>File a complaint with your state insurance commissioner</strong> if your insurer is not following the proper appeals process or is unreasonably delaying decisions.</li>
</ol>

<div class="key-takeaway" style="border-left: 4px solid #22c55e; padding: 1rem 1.25rem; background: #f0fdf4; margin: 1.5rem 0;">
    <strong>Upload your EOB and bill to BillKarma.</strong> We automatically compare the two, flag discrepancies, identify denial codes worth appealing, and tell you exactly where you may be overpaying. <a href="/scan">Get started free.</a>
</div>

<h2 id="sources">Sources</h2>

<ul class="sources-list">
    <li><a href="https://www.cms.gov/cciio/resources/files/uploads/uniform_glossary_final.pdf" target="_blank" rel="noopener">CMS: Uniform Glossary of Health Coverage and Medical Terms</a></li>
    <li><a href="https://www.dol.gov/sites/dolgov/files/ebsa/about-ebsa/our-activities/resource-center/faqs/aca-part-vi.pdf" target="_blank" rel="noopener">DOL: Claims and Appeal Procedures Under the ACA</a></li>
    <li><a href="https://www.kff.org/private-insurance/issue-brief/patient-rights-to-appeal-private-health-plan-denials/" target="_blank" rel="noopener">KFF: Patient Rights to Appeal Private Health Plan Denials</a></li>
    <li><a href="https://www.cms.gov/medicare/coding-billing/claim-adjustment-reason-codes" target="_blank" rel="noopener">CMS: Claim Adjustment Reason Codes (CARC) and Remittance Advice Remark Codes (RARC)</a></li>
    <li><a href="https://www.healthcare.gov/appeal-insurance-company-decision/internal-appeals/" target="_blank" rel="noopener">HealthCare.gov: How to Appeal a Health Insurance Decision</a></li>
</ul>

</article>""",
})
